<a href="https://colab.research.google.com/github/Yash-Patil09/Deep_Learning-/blob/main/Pytorch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Creating Tensors**

In [4]:
scaler = torch.tensor([5.0])
vector = torch.tensor([1,2,3])
matrix = torch.tensor([[1,2],[3,4]])
cube = torch.tensor([[1,2,3],[3,4,5],[7,8,9]])

#printing them
print(f"Scalar: {scaler}, Shape: {scaler.shape}")
print(f"Vector: {vector}, Shape: {vector.shape}")
print(f"Matrix: {matrix}, Shape: {matrix.shape}")
print(f"Cube:  {cube}, Shape: {cube.shape}")

Scalar: tensor([5.]), Shape: torch.Size([1])
Vector: tensor([1, 2, 3]), Shape: torch.Size([3])
Matrix: tensor([[1, 2],
        [3, 4]]), Shape: torch.Size([2, 2])
Cube:  tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]]), Shape: torch.Size([3, 3])


In [5]:
list = [1,2,3,4,5]
tensor_1d = torch.tensor(list)
print(f"List : {tensor_1d}")

list_2d = [[133,44,55],[567,33,232]]
tensor_2d = torch.tensor(list_2d)
print(f"List : {tensor_2d}")

List : tensor([1, 2, 3, 4, 5])
List : tensor([[133,  44,  55],
        [567,  33, 232]])


In [6]:
np_array = np.array([1,2,33,44])
tensor_fromNUMPy = torch.from_numpy(np_array)

print(tensor_fromNUMPy)

tensor([ 1,  2, 33, 44])


In [7]:
tens = torch.tensor([1,2,3,4])
num = tens.numpy()

print(num)

[1 2 3 4]


In [8]:
np_array[0] = 100
print(f"NP array: {np_array}")
print(f"Tensor:{tensor_fromNUMPy}")


NP array: [100   2  33  44]
Tensor:tensor([100,   2,  33,  44])


Modification in one affects the other

so lets make the clone

In [9]:
tensor_clone = torch.from_numpy(np_array).clone()
tensor_copy = torch.from_numpy(np_array.copy())

print(tensor_clone)
print(tensor_copy)


tensor([100,   2,  33,  44])
tensor([100,   2,  33,  44])


**Factory Functions**

In [10]:
zeroes = torch.zeros(3,4)
ones = torch.ones(2,2,3)
full = torch.full((2,3),7)

print(zeroes)
print(ones)
print(full)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
tensor([[7, 7, 7],
        [7, 7, 7]])


In [11]:
identity = torch.eye(6)
print(identity)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])


In [12]:
#Random Tensors

random_uniform = torch.rand(2,3)
random_normal = torch.randn(2,3)
random_int = torch.randint(0,10,(2,3))

print(random_uniform)
print(random_normal)
print(random_int)

tensor([[0.3712, 0.3838, 0.4073],
        [0.5150, 0.6022, 0.0074]])
tensor([[-0.7790, -0.4517,  1.1791],
        [ 0.2732, -1.1575,  0.4228]])
tensor([[6, 6, 1],
        [0, 6, 4]])


In [13]:
#Sequences

arange = torch.arange(0,10,2)
linspace = torch.linspace(0,1,4)
logspace = torch.logspace(0,1,5)

print(arange)
print(linspace)
print(logspace)

tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.3333, 0.6667, 1.0000])
tensor([ 1.0000,  1.7783,  3.1623,  5.6234, 10.0000])


**Properties and Attributes**

In [14]:
tensor = torch.rand(2,3,4)
print(tensor)

tensor([[[0.6017, 0.6274, 0.0799, 0.9930],
         [0.0854, 0.1489, 0.1745, 0.2158],
         [0.0813, 0.3266, 0.8176, 0.4838]],

        [[0.2294, 0.2292, 0.7893, 0.6161],
         [0.1642, 0.2381, 0.4621, 0.0630],
         [0.6992, 0.2156, 0.2005, 0.9569]]])


In [15]:
#Shape and Size

print(f"Shape: {tensor.shape}")
print(f'Size: {tensor.size()}')
print(f"Dimension: {tensor.ndim}")
print(f"Total No. of Elements: {tensor.numel()}")

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Dimension: 3
Total No. of Elements: 24


In [16]:
# Data type and device
print(f"Data type: {tensor.dtype}")
print(f"Device: {tensor.device}")
print(f"Memory layout: {tensor.layout}")

# Check properties
print(f"Requires grad: {tensor.requires_grad}")
print(f"Is leaf: {tensor.is_leaf}")
print(f"Is contiguous: {tensor.is_contiguous()}")

Data type: torch.float32
Device: cpu
Memory layout: torch.strided
Requires grad: False
Is leaf: True
Is contiguous: True


In [17]:
#Type Conversion

x = torch.tensor([1,2,4])
print(x.dtype)

x_double = x.double()
print(x_double.dtype)

x_float = x.float()
print(x_float.dtype)
x_float = x.float()
x_long = x.long()
x_bool = x.bool()

torch.int64
torch.float64
torch.float32


**Indexing and Slicing**

In [18]:
x = torch.tensor([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [19]:
#Single elememt
print(f'Element at x[2,3] :{x[2,3]}')
print(f"Element at 7: {x[1,2]}")

Element at x[2,3] :12
Element at 7: 7


In [20]:
#Row and column access
print(f"First row: {x[0]}")
print(f"Last Column: {x[:,-1]}")
print(f"2row and 2nd column: {x[1],x[:,-3]}")

First row: tensor([1, 2, 3, 4])
Last Column: tensor([ 4,  8, 12])
2row and 2nd column: (tensor([5, 6, 7, 8]), tensor([ 2,  6, 10]))


In [21]:
# Multiple rows/columns
print(f"First two rows: \n{x[:2,:]}")
print(f"Last two columns: \n{x[:, -2:]}")

First two rows: 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
Last two columns: 
tensor([[ 3,  4],
        [ 7,  8],
        [11, 12]])


In [22]:
# Boolean indexing
x = torch.randn(3, 4)
mask = x > 0
positive_elements = x[mask]
print(f"Positive elements: {positive_elements}")
print(f"Number of elem:{x[mask].numel()}")

Positive elements: tensor([0.1117, 0.8755, 0.6757, 0.1483, 1.0738, 0.2894, 0.8639])
Number of elem:7


In [23]:
# Conditional selection
x = torch.tensor([1, -2, 3, -4, 5])
positive_x = torch.where(x > 0, x, torch.tensor(0))
print(f"Replace negative with 0: {positive_x}")

Replace negative with 0: tensor([1, 0, 3, 0, 5])


In [24]:
# Advanced indexing with tensors
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Select specific elements
row_indices = torch.tensor([0, 1, 2])
col_indices = torch.tensor([0, 1, 2])
diagonal = x[row_indices, col_indices]
print(f"Diagonal elements: {diagonal}")

# Fancy indexing
indices = torch.tensor([[0, 1], [2, 0]])
selected = x[indices]
print(f"Selected elements: \n{selected}")

Diagonal elements: tensor([1, 5, 9])
Selected elements: 
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [1, 2, 3]]])


**Slicing Ops**

In [25]:
x = torch.arange(20).reshape(4,5)
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [26]:
print(f"Every other row: {x[::2]}")

Every other row: tensor([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]])


In [27]:
# Every other column
print(f"Every other column: {x[:, ::2]}")

Every other column: tensor([[ 0,  2,  4],
        [ 5,  7,  9],
        [10, 12, 14],
        [15, 17, 19]])


In [28]:
# Reverse operations
print(f"Reversed rows: \n{torch.flip(x, dims=[0])}")
print(f"Reversed columns: \n{torch.flip(x, dims=[1])}")

# Complex slicing
print(f"Middle 2x3 submatrix: \n{x[1:3, 1:4]}")

Reversed rows: 
tensor([[15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4]])
Reversed columns: 
tensor([[ 4,  3,  2,  1,  0],
        [ 9,  8,  7,  6,  5],
        [14, 13, 12, 11, 10],
        [19, 18, 17, 16, 15]])
Middle 2x3 submatrix: 
tensor([[ 6,  7,  8],
        [11, 12, 13]])


**Reshaping and Manipulating Tensors**

In [29]:
x = torch.arange(24)
print(f"Original: {x}")

Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


In [30]:
# Reshape (view)
x_2d = x.view(4, 6)
x_3d = x.view(2, 3, 4)
x_4d = x.view(2, 2, 2, 3)

print(f"2D view (4x6): \n{x_2d}")
print(f"3D view (2x3x4): \n{x_3d}")
print(f"4D view (2x2x2x3): \n{x_4d}")

2D view (4x6): 
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
3D view (2x3x4): 
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
4D view (2x2x2x3): 
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]])


**Mathematical Operations**

In [31]:
x =  torch.tensor([1.0,2.0,3.0])
y =  torch.tensor([4.0,5.0,6.0])

In [35]:
#Add
add1 = x + y
add2 = torch.add(x,y)
add3 = x.add(y)

print(add2)

tensor([5., 7., 9.])


In [37]:
from re import sub
#Sub

sub1 = y - x
sub2 = torch.sub(y,x)

print(sub2)

tensor([3., 3., 3.])


In [39]:
#Mul
mul1 = x * y
mul2 = torch.mul(x,y)

print(mul2)

tensor([ 4., 10., 18.])


same for division

In [42]:
#pow
pow = x ** 2
pow2 = torch.pow(x,2)

print(pow2)

tensor([1., 4., 9.])


In [43]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0])

# Trigonometric functions
sin_x = torch.sin(x)
cos_x = torch.cos(x)
tan_x = torch.tan(x)

# Exponential and logarithmic
exp_x = torch.exp(x)
log_x = torch.log(x)
log10_x = torch.log10(x)
sqrt_x = torch.sqrt(x)

# Rounding functions
x_float = torch.tensor([1.2, 2.7, 3.1, 4.9])
floor_x = torch.floor(x_float)
ceil_x = torch.ceil(x_float)
round_x = torch.round(x_float)

# Absolute value and sign
x_mixed = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
abs_x = torch.abs(x_mixed)
sign_x = torch.sign(x_mixed)

print(f"Sin: {sin_x}")
print(f"Exp: {exp_x}")
print(f"Floor: {floor_x}")
print(f"Absolute: {abs_x}")
print(f"Sign: {sign_x}")

Sin: tensor([ 0.8415,  0.9093,  0.1411, -0.7568])
Exp: tensor([ 2.7183,  7.3891, 20.0855, 54.5981])
Floor: tensor([1., 2., 3., 4.])
Absolute: tensor([2., 1., 0., 1., 2.])
Sign: tensor([-1., -1.,  0.,  1.,  1.])


In [44]:
x = torch.tensor([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0],
                  [7.0, 8.0, 9.0]])

In [45]:
sum_all = torch.sum(x)
print(sum_all)

tensor(45.)


In [46]:
sum_dim0 = torch.sum(x, dim=0)
sum_dim1 = torch.sum(x, dim=1)

print(f"Sum along dim 0: {sum_dim0}")
print(f"Sum along dim 1: {sum_dim1}")


Sum along dim 0: tensor([12., 15., 18.])
Sum along dim 1: tensor([ 6., 15., 24.])


In [48]:
# Mean operations
mean_all = torch.mean(x)
mean_dim0 = torch.mean(x, dim=0)
mean_dim1 = torch.mean(x, dim=1)

print(f'Mean of all elements: {mean_all}')
print(f'Mean along dim 0: {mean_dim0}')
print(f'Mean along dim 1: {mean_dim1}')

Mean of all elements: 5.0
Mean along dim 0: tensor([4., 5., 6.])
Mean along dim 1: tensor([2., 5., 8.])


In [52]:
#minMAX
min_all = torch.min(x)
max_all = torch.max(x)
min_dim0, min_indices0 = torch.min(x, dim=0)  # Returns values and indices
max_dim0, max_indices0 = torch.max(x, dim=1)


print(f'Min of all elements: {min_all}')
print(f'Max of all elements: {max_all}')
print(f'Min along dim 0: {min_dim0}')
print(f'Max along dim 0: {max_dim0}')

Min of all elements: 1.0
Max of all elements: 9.0
Min along dim 0: tensor([1., 2., 3.])
Max along dim 0: tensor([3., 6., 9.])


**Linear Algebra Operations**

In [55]:
A = torch.randn(3,4)
B = torch.randn(4, 2)

print(A)
print(B)

tensor([[ 0.3875, -0.5665, -0.6645, -1.7976],
        [-0.0128, -1.3879, -0.6684, -0.4300],
        [-0.5137,  0.9004,  1.7923, -0.7146]])
tensor([[-0.8560,  0.6091],
        [ 0.0689,  0.8751],
        [-0.6537,  0.5321],
        [-0.5265, -0.9190]])


In [54]:
#Matrix Multiplication

c1 = torch.mm(A,B)
c2 = torch.matmul(A,B)
c3 = A @ B

print(c2)

tensor([[ 1.2998,  0.8620],
        [ 0.2502,  0.6358],
        [-0.7970, -0.9786]])


In [56]:
batch_A = torch.randn(5,3,4)
batch_B = torch.randn(5,4,2)

print(batch_A)
print(batch_B)



tensor([[[-6.2714e-01,  8.1058e-01, -1.4553e+00,  4.3612e-01],
         [ 1.2391e+00, -1.1809e+00,  4.2150e-01,  1.0821e+00],
         [-1.4929e+00, -6.9643e-02,  1.5297e+00, -1.2650e+00]],

        [[ 4.3439e-01, -9.4186e-01, -2.5393e-01,  1.0203e+00],
         [-1.5448e+00, -1.7402e-01,  1.1004e+00,  2.0287e-01],
         [ 1.0169e+00, -1.5874e-01, -1.2628e+00, -1.0017e+00]],

        [[ 6.7619e-01,  7.2440e-01, -6.2300e-01,  8.7230e-01],
         [-6.5799e-01,  7.1697e-01,  4.3245e-01,  1.5389e+00],
         [-1.0742e+00,  6.2179e-01, -1.5840e-03, -1.8081e+00]],

        [[ 1.1579e+00,  3.9555e-01,  1.4797e+00, -1.7083e+00],
         [ 2.4333e-01, -5.3665e-01,  2.3511e-01, -9.9144e-01],
         [ 3.7941e-02,  1.1061e+00,  1.0019e-01, -8.1751e-01]],

        [[ 1.9903e+00, -7.2266e-01, -6.2885e-02,  5.6386e-01],
         [ 1.5118e-01,  1.0842e+00,  1.6699e-01, -1.2934e+00],
         [ 8.1294e-01, -7.8471e-01, -1.1769e+00,  6.9975e-01]]])
tensor([[[-1.3045, -0.1528],
         [ 0.465

In [57]:
batch_c1 = torch.bmm(batch_A, batch_B)
batch_c2 = torch.matmul(batch_A, batch_B)

print(batch_c1)

tensor([[[-1.0182, -1.3665],
         [-3.0197,  2.2890],
         [ 5.2395,  0.0451]],

        [[ 1.5723,  0.2201],
         [ 1.4704, -2.9791],
         [-1.9736,  1.9603]],

        [[-1.3300,  2.0980],
         [-0.1101,  2.8054],
         [ 2.8721, -0.3574]],

        [[ 4.9709, -1.7541],
         [ 2.2733, -0.9283],
         [ 1.3329, -0.1022]],

        [[ 0.6815, -0.5691],
         [ 1.6437,  2.0431],
         [-0.2486,  0.0828]]])


In [58]:
# Dot product and cross product
v1 = torch.tensor([1.0, 2.0, 3.0])
v2 = torch.tensor([4.0, 5.0, 6.0])

dot_product = torch.dot(v1, v2)
cross_product = torch.cross(v1, v2)

print(f"Dot product: {dot_product}")
print(f"Cross product: {cross_product}")

Dot product: 32.0
Cross product: tensor([-3.,  6., -3.])


In [61]:
# Advanced linear algebra
A = torch.randn(4, 4)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = torch.linalg.eig(A) # Use torch.linalg.eig for both eigenvalues and eigenvectors

# Singular Value Decomposition
U, S, Vh = torch.linalg.svd(A) # Use torch.linalg.svd

# Matrix determinant and inverse
det_A = torch.linalg.det(A) # Use torch.linalg.det
inv_A = torch.linalg.inv(A) # Use torch.linalg.inv

# Norm operations
frobenius_norm = torch.linalg.norm(A, ord='fro')  # Use torch.linalg.norm with ord='fro'
l2_norm = torch.linalg.norm(v1, ord=2)            # Use torch.linalg.norm with ord=2
l1_norm = torch.linalg.norm(v1, ord=1)            # Use torch.linalg.norm with ord=1


print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors: \n{eigenvectors}")
print(f"U: \n{U}")
print(f"S: \n{S}")
print(f"Vh: \n{Vh}")
print(f"Determinant: {det_A}")
print(f"Inverse: \n{inv_A}")
print(f"Frobenius norm: {frobenius_norm}")
print(f"L2 norm: {l2_norm}")
print(f"L1 norm: {l1_norm}")

Eigenvalues: tensor([-2.2106+0.0000j,  1.3685+0.0000j,  0.1551+1.1671j,  0.1551-1.1671j])
Eigenvectors: 
tensor([[ 0.5700+0.0000j,  0.7031+0.0000j, -0.0427-0.3563j, -0.0427+0.3563j],
        [-0.6569+0.0000j,  0.6661+0.0000j, -0.7327+0.0000j, -0.7327-0.0000j],
        [ 0.4733+0.0000j, -0.2469+0.0000j, -0.4325+0.1806j, -0.4325-0.1806j],
        [-0.1400+0.0000j, -0.0317+0.0000j, -0.0223-0.3378j, -0.0223+0.3378j]])
U: 
tensor([[ 0.6749, -0.2045, -0.7040, -0.0842],
        [-0.5258,  0.5401, -0.6475, -0.1120],
        [-0.5153, -0.8065, -0.2717,  0.1008],
        [ 0.0507,  0.1264, -0.1060,  0.9850]])
S: 
tensor([2.7793, 2.2739, 1.6308, 0.4069])
Vh: 
tensor([[-0.2013,  0.1407, -0.5940, -0.7661],
        [ 0.7332, -0.3024,  0.3355, -0.5084],
        [-0.6336, -0.1856,  0.6519, -0.3731],
        [-0.1433, -0.9243, -0.3311,  0.1246]])
Determinant: -4.193716049194336
Inverse: 
tensor([[ 0.1883,  0.5032, -0.1526, -0.2686],
        [ 0.3328,  0.2296, -0.1169, -2.2397],
        [-0.3873,  0.024

In [2]:
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA device count: {torch.cuda.device_count()}")

CUDA available: False
CUDA device count: 0


**Sorting and Ordering**

In [6]:
x = torch.tensor([3, 1, 4, 1, 5, 9, 2, 6])

sorted_values , sorted_indices = torch.sort(x)
sorted_desc , sorted_indices_desc = torch.sort(x, descending=True)

print(f'Sorted values: {sorted_values}')
print(f'Sorted indices: {sorted_indices}')
print(f'Sorted in descending order: {sorted_desc}')
print(f'Sorted indices in descending order: {sorted_indices_desc}')

Sorted values: tensor([1, 1, 2, 3, 4, 5, 6, 9])
Sorted indices: tensor([1, 3, 6, 0, 2, 4, 7, 5])
Sorted in descending order: tensor([9, 6, 5, 4, 3, 2, 1, 1])
Sorted indices in descending order: tensor([5, 7, 4, 2, 0, 6, 1, 3])


In [8]:
y = torch.randn(3,4)
print(y)
sorted_values , sorted_indices = torch.sort(y)
sorted_desc , sorted_indices_desc = torch.sort(y, descending=True)

print(f'Sorted values: {sorted_values}')
print(f'Sorted indices: {sorted_indices}')
print(f'Sorted in descending order: {sorted_desc}')
print(f'Sorted indices in descending order: {sorted_indices_desc}')


tensor([[ 1.3203,  0.5153,  0.9079,  0.6897],
        [ 1.6206, -0.7875, -0.0500, -0.4639],
        [ 2.1329, -0.6817, -0.5304,  0.5189]])
Sorted values: tensor([[ 0.5153,  0.6897,  0.9079,  1.3203],
        [-0.7875, -0.4639, -0.0500,  1.6206],
        [-0.6817, -0.5304,  0.5189,  2.1329]])
Sorted indices: tensor([[1, 3, 2, 0],
        [1, 3, 2, 0],
        [1, 2, 3, 0]])
Sorted in descending order: tensor([[ 1.3203,  0.9079,  0.6897,  0.5153],
        [ 1.6206, -0.0500, -0.4639, -0.7875],
        [ 2.1329,  0.5189, -0.5304, -0.6817]])
Sorted indices in descending order: tensor([[0, 2, 3, 1],
        [0, 2, 3, 1],
        [0, 3, 2, 1]])


**Set Operations**

In [9]:
x = torch.tensor([1, 2, 3, 4, 5])
y = torch.tensor([3, 4, 5, 6, 7])

In [10]:
intersection = x[torch.isin(x,y)]
union = torch.unique(torch.cat([x,y]))
difference =  x[~torch.isin(x,y)]


print(f'Intersection: {intersection}')
print(f'Union: {union}')
print(f'Difference: {difference}')

Intersection: tensor([3, 4, 5])
Union: tensor([1, 2, 3, 4, 5, 6, 7])
Difference: tensor([1, 2])


In [11]:
from torch.autograd import Function

class SquareFunction(Function):
    @staticmethod
    def forward(ctx, input):
        # Save input for backward pass
        ctx.save_for_backward(input)
        return input ** 2

    @staticmethod
    def backward(ctx, grad_output):
        # Retrieve saved input
        input, = ctx.saved_tensors
        # Compute gradient: d/dx(x^2) = 2x
        grad_input = 2 * input * grad_output
        return grad_input

# Use custom function
square = SquareFunction.apply
x = torch.tensor([2.0, 3.0, 4.0], requires_grad=True)
y = square(x)
y.sum().backward()
print(f"Input: {x}")
print(f"Output: {y}")
print(f"Gradient: {x.grad}")

Input: tensor([2., 3., 4.], requires_grad=True)
Output: tensor([ 4.,  9., 16.], grad_fn=<SquareFunctionBackward>)
Gradient: tensor([4., 6., 8.])


**Image Processing**

In [12]:
def normalize_image_batch(images, mean, std):
    """
    Normalize a batch of images
    Args:
        images: (B, C, H, W) tensor
        mean: (C,) tensor
        std: (C,) tensor
    """
    # Reshape mean and std for broadcasting
    mean = mean.view(1, -1, 1, 1)
    std = std.view(1, -1, 1, 1)

    return (images - mean) / std

# Example usage
batch_size, channels, height, width = 32, 3, 224, 224
images = torch.randn(batch_size, channels, height, width)
mean = torch.tensor([0.485, 0.456, 0.406])
std = torch.tensor([0.229, 0.224, 0.225])

normalized_images = normalize_image_batch(images, mean, std)
print(f"Normalized images shape: {normalized_images.shape}")

# Data augmentation with tensors
def random_crop(image, size):
    """Random crop of image tensor"""
    c, h, w = image.shape
    new_h, new_w = size

    if h < new_h or w < new_w:
        raise ValueError("Crop size larger than image")

    top = torch.randint(0, h - new_h + 1, (1,)).item()
    left = torch.randint(0, w - new_w + 1, (1,)).item()

    return image[:, top:top+new_h, left:left+new_w]

# Example
image = torch.randn(3, 256, 256)
cropped = random_crop(image, (224, 224))
print(f"Cropped image shape: {cropped.shape}")

Normalized images shape: torch.Size([32, 3, 224, 224])
Cropped image shape: torch.Size([3, 224, 224])


**Time Series Analysis**

In [13]:
# Create sliding windows for time series
def create_sequences(data, seq_length):
    """Create sequences for time series prediction"""
    sequences = []
    targets = []

    for i in range(len(data) - seq_length):
        seq = data[i:i+seq_length]
        target = data[i+seq_length]
        sequences.append(seq)
        targets.append(target)

    return torch.stack(sequences), torch.stack(targets)

# Generate sample time series data
time_steps = 1000
t = torch.linspace(0, 4*torch.pi, time_steps)
data = torch.sin(t) + 0.1 * torch.randn(time_steps)

# Create sequences
seq_length = 50
sequences, targets = create_sequences(data, seq_length)

print(f"Sequences shape: {sequences.shape}")
print(f"Targets shape: {targets.shape}")

# Moving average
def moving_average(data, window_size):
    """Compute moving average"""
    # Create convolution kernel
    kernel = torch.ones(window_size) / window_size
    # Add batch and channel dimensions
    kernel = kernel.view(1, 1, -1)
    data = data.view(1, 1, -1)

    # Apply convolution
    smoothed = torch.nn.functional.conv1d(data, kernel, padding=window_size//2)
    return smoothed.squeeze()

smoothed_data = moving_average(data, window_size=10)
print(f"Smoothed data shape: {smoothed_data.shape}")

Sequences shape: torch.Size([950, 50])
Targets shape: torch.Size([950])
Smoothed data shape: torch.Size([1001])


**Natural Language Processing**

In [16]:
# Word embedding lookup
def create_embedding_layer(vocab_size, embedding_dim):
    """Create embedding layer"""
    return torch.nn.Embedding(vocab_size, embedding_dim)

# Text processing
def pad_sequences(sequences, max_length, pad_value=0):
    """Pad sequences to same length"""
    batch_size = len(sequences)
    padded = torch.full((batch_size, max_length), pad_value, dtype=torch.long)

    for i, seq in enumerate(sequences):
        length = min(len(seq), max_length)
        padded[i, :length] = torch.tensor(seq[:length])

    return padded

# Example usage
vocab_size = 10000
embedding_dim = 300
embedding = create_embedding_layer(vocab_size, embedding_dim)

# Sample sequences (token indices)
sequences = [
    [1, 2, 3, 4, 5],
    [6, 7, 8],
    [9, 10, 11, 12, 13, 14, 15]
]

padded_sequences = pad_sequences(sequences, max_length=10)
embeddings = embedding(padded_sequences)

print(f"Padded sequences shape: {padded_sequences.shape}")
print(f"Embeddings shape: {embeddings.shape}")



Padded sequences shape: torch.Size([3, 10])
Embeddings shape: torch.Size([3, 10, 300])
